# Generated by Django 3.2.7 on 2021-11-13 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('twitchEvents', '0003_alter_logentry_eventid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='logentry',
            name='type',
        ),
        migrations.AddField(
            model_name='logentry',
            name='game',
            field=models.CharField(default='N/A', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='logentry',
            name='title',
            field=models.CharField(default='N/A', max_length=200),
            preserve_default=False,
        ),
    ]
