# Generated by Django 3.2.7 on 2021-12-04 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('twitchEvents', '0004_auto_20211113_1754'),
    ]

    operations = [
        migrations.CreateModel(
            name='UpdateLogEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel', models.CharField(max_length=50)),
                ('recieved', models.DateTimeField()),
                ('game', models.CharField(max_length=100)),
                ('title', models.CharField(max_length=200)),
            ],
        ),
        migrations.RemoveField(
            model_name='logentry',
            name='eventID',
        ),
    ]
