# Generated by Django 3.2.7 on 2021-12-13 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('twitchEvents', '0006_auto_20211206_1212'),
    ]

    operations = [
        migrations.AddField(
            model_name='logentry',
            name='eventid',
            field=models.CharField(default='N/A', max_length=100),
            preserve_default=False,
        ),
    ]
