# Generated by Django 3.2.7 on 2022-02-27 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('twitchEvents', '0008_channelevents'),
    ]

    operations = [
        migrations.RenameField(
            model_name='channelevents',
            old_name='channel',
            new_name='channelID',
        ),
        migrations.AddField(
            model_name='channelevents',
            name='channelName',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
    ]
